import { Vacancy, ProgramOption } from './types';

export const FTMM_PRODI_LIST: ProgramOption[] = [
  { id: '1', name: 'Robotika & AI', slug: 'robotika-ai', colorHex: '#9CA3AF' },
  { id: '2', name: 'Teknik Elektro', slug: 'teknik-elektro', colorHex: '#F4C542' },
  { id: '3', name: 'Teknik Industri', slug: 'teknik-industri', colorHex: '#2563EB' },
  { id: '4', name: 'Sains Data', slug: 'sains-data', colorHex: '#A855F7' },
  { id: '5', name: 'Rekayasa Nano', slug: 'rekayasa-nano', colorHex: '#EF4444' },
];

export const INITIAL_MOCK_VACANCIES: Vacancy[] = [
  {
    id: 'vac-1',
    title: 'Design Engineering',
    company: 'Kreatif 3D',
    location: 'Jakarta',
    source_url: 'https://www.linkedin.com/jobs/view/4444824507/',
    description: 'Strong foundation in Design Engineering and Product Design, with the ability to contribute to practical, manufacturable solutions. Knowledge of Mechanical Engineering principles for structural integrity, materials selection, and performance analysis. Proficiency in Computer-Aided Design (CAD) tools (e.g., SolidWorks, Fusion 360, or similar) for modeling, assemblies, and technical drawings. Basic understanding of Electrical Engineering concepts is beneficial for integrating simple electronic components into designs. Currently pursuing or recently completed a degree in Mechanical Engineering, Design Engineering, Product Design, or a related field. Some Experience in 3D printing technologies, additive manufacturing processes, and rapid prototyping. Attention to detail, problem-solving mindset, and ability to work collaboratively in a multidisciplinary team.',
    prodi_tags: ['Robotika & AI', 'Teknik Industri'],
    is_active: false,
    created_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
  {
    id: 'vac-2',
    title: 'AI/ML Engineer',
    company: 'Artajasa Pembayaran Elektronis',
    location: 'Tangerang',
    source_url: 'https://www.linkedin.com/jobs/view/4440659663/',
    description: 'Final-year student or fresh graduate in Computer Science, Artificial Intelligence, Data Science, Information Technology, or a related field. Basic understanding of Machine Learning, Deep Learning, or Artificial Intelligence concepts. Familiarity with Python and common AI/ML libraries such as Pandas, NumPy, Scikit-learn, TensorFlow, or PyTorch. Basic knowledge of SQL and data processing techniques. Familiarity with Generative AI, Large Language Models (LLMs), or Retrieval-Augmented Generation (RAG) is a plus. Familiarity dengan LLM orchestration tools (Dify, LangChain, LangGraph). Strong analytical thinking, curiosity, and willingness to learn new technologies. Good communication skills and the ability to work collaboratively in a team environment. Available for a full-time internship period.',
    prodi_tags: ['Robotika & AI', 'Sains Data'],
    is_active: false,
    created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
  {
    id: 'vac-3',
    title: 'Industrial Engineering',
    company: 'APP Group',
    location: 'Serang',
    source_url: 'https://www.linkedin.com/jobs/view/4436071250/',
    description: 'Undergraduate student majoring in Industrial Engineering / Management / Statistics / Engineering (Semester 5–8 only). Strong analytical thinking and problem-solving mindset. Proactive, eager to learn, and able to work in a dynamic environment. Comfortable working in an full time onsite arrangement at Serang Mill.',
    prodi_tags: ['Teknik Industri'],
    is_active: false,
    created_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 3 * 86400000).toISOString(),
  },
  {
    id: 'vac-4',
    title: 'Process Design Engineer Production Capacity Planning',
    company: 'PT Astra International Tbk',
    location: 'Karawang',
    source_url: 'https://www.linkedin.com/jobs/view/4418177960/',
    description: 'Mahasiswa AKTIF, minimal tahun kedua atau ketiga. Bersedia menjalani magang secara langsung di lokasi (onsite). Akrab/familiar dengan manajemen manufaktur & produksi. Cekatan dalam kerja sama tim berbasis data serta memiliki kemampuan komunikasi yang baik. Mampu mengoperasikan fungsi-fungsi dasar Excel.',
    prodi_tags: ['Teknik Industri'],
    is_active: false,
    created_at: new Date(Date.now() - 4 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 4 * 86400000).toISOString(),
  },
  {
    id: 'vac-5',
    title: 'Supply Chain / Operations',
    company: 'Adidas',
    location: 'Jakarta',
    source_url: 'https://www.linkedin.com/jobs/view/4423623900/',
    description: 'Engineering, Supply Chain or similar field of study. In a degree program or have completed a minimum degree program. Good command in English spoken and written language. Microsoft Office. Creative, proactive and out of the box thinking. Ability to work with minimum supervision.',
    prodi_tags: ['Teknik Industri'],
    is_active: false,
    created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 5 * 86400000).toISOString(),
  },
  {
    id: 'vac-6',
    title: 'Data Scientist',
    company: 'Tiket.com',
    location: 'Jakarta',
    source_url: 'https://www.linkedin.com/jobs/view/4442038368/',
    description: 'Having background in math, statistics, and/or computer science. Having basic knowledge of programming paradigm (structured / object oriented programming). Having basic knowledge of machine learning and data analysis. Having basic knowledge of NLP, Information Retrieval, Recommender System, and/or Deep Learning is a plus point. Familiar with python and some data science-related libraries in python, i.e., numpy, pandas and scikit learn. Familiar with SQL. Willing and able to read and understand scientific paper. Strong verbal and written communication skills. Work with stakeholders throughout the organization to identify opportunities for leveraging company data to drive business solutions. Mine and analyze data from company databases to drive optimization and improvement of product development, marketing techniques and business strategies. Develop custom data models and algorithms to apply to data sets. Use predictive modeling to increase and optimize customer experiences, revenue generation, ad targeting and other business outcomes. Develop company A/B testing framework and test model quality. Coordinate with different functional teams to implement models and monitor outcomes. Develop processes and tools to monitor and analyze model performance and impact to business. Writing reports and documentations based on discussions and experimentations.',
    prodi_tags: ['Sains Data', 'Robotika & AI'],
    is_active: false,
    created_at: new Date(Date.now() - 6 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 6 * 86400000).toISOString(),
  },
  {
    id: 'vac-7',
    title: 'Production Technician',
    company: 'Siemens',
    location: 'Jakarta',
    source_url: 'https://www.linkedin.com/jobs/view/4437566726/',
    description: 'Undergraduate student of bachelor\'s degree in electrical engineering. Recommendation letter from the university. Able to do minimum of three months internship. Willing to fully comply with the regulations during the internship. English and Bahasa Indonesia proficiencies.',
    prodi_tags: ['Teknik Elektro'],
    is_active: false,
    created_at: new Date(Date.now() - 7 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 7 * 86400000).toISOString(),
  },
  {
    id: 'vac-8',
    title: 'Maintenance Engineer',
    company: 'PT Akasha Wira International Tbk',
    location: 'Bogor',
    source_url: 'https://www.linkedin.com/jobs/view/4440405804/',
    description: 'Candidate must possess at least a Bachelor\'s Degree in major: Electrical (arus lemah) with a minimum GPA of 3.5. Fresh graduates are encouraged to apply. Having good communication skills, Open Minded, Hungry, Curious & Fast Learner and Technology Savvy. Willing to place in Wanaherang, Kab. Bogor.',
    prodi_tags: ['Teknik Elektro', 'Teknik Industri'],
    is_active: false,
    created_at: new Date(Date.now() - 8 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 8 * 86400000).toISOString(),
  },
  {
    id: 'vac-9',
    title: 'Supply Chain',
    company: 'Siloam Hospital Groups',
    location: 'Tangerang',
    source_url: 'https://www.linkedin.com/jobs/view/4442604524/',
    description: 'Final-year student or fresh graduate pursuing a Bachelor\'s degree in Operations Management, Industrial Engineering, Supply Chain Management, Information Systems, or a related field. Basic understanding of business processes and operational workflows. Familiarity with inventory management or supply chain concepts is an advantage. Strong analytical thinking and attention to detail. Good communication and coordination skills with the ability to work across teams. Proficient in Microsoft Excel (Pivot Tables, formulas, and basic data analysis). Eager to learn, proactive, and able to work in a fast-paced environment. Full WFO Lippo Karawaci, Tangerang.',
    prodi_tags: ['Teknik Industri'],
    is_active: false,
    created_at: new Date(Date.now() - 9 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 9 * 86400000).toISOString(),
  },
  {
    id: 'vac-10',
    title: 'Non-Destructive Testing',
    company: 'McDermott International Ltd',
    location: 'Batam',
    source_url: 'https://www.linkedin.com/jobs/view/4438190114/',
    description: 'Currently pursuing a Diploma or Bachelor\'s Degree in Mechanical Engineering, Materials Engineering, Industrial Engineering, Naval Architecture, or a related field. Must remain an active university student throughout the internship period. Interest in Quality Control, Inspection, and Non-Destructive Testing (NDT). Applicants should not be participating in another internship program. Applicants should have strong communication skills and ability to work in a team environment. Attention to detail and a willingness to follow instructions.',
    prodi_tags: ['Teknik Industri'],
    is_active: false,
    created_at: new Date(Date.now() - 10 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 10 * 86400000).toISOString(),
  },
  {
    id: 'vac-11',
    title: 'Yard Welding Engineering',
    company: 'McDermott International Ltd',
    location: 'Batam',
    source_url: 'https://www.linkedin.com/jobs/view/4443323696/',
    description: 'Active college student in S1 (Material Engineering, Mechanical Engineering, Electrical Engineering). Internship placement is available in McDermott Batam Fabrication Yard. Applicants should not be participating in another internship program. Applicants should have strong communication skills and ability to work in a team environment. Attention to detail and a willingness to follow instructions.',
    prodi_tags: ['Rekayasa Nano', 'Teknik Elektro'],
    is_active: true,
    created_at: new Date(Date.now() - 11 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 11 * 86400000).toISOString(),
  },
  {
    id: 'vac-12',
    title: 'Machine Learning Engineer',
    company: 'Terra Softech',
    location: 'Aceh',
    source_url: 'https://www.linkedin.com/jobs/view/4443141450/',
    description: 'Educational Background: Currently pursuing a Graduate degree in Computer Science, Electrical Engineering, or a related technical field. Programming Skills: Proficiency in Python and familiarity with go and CUDA is a plus. Foundational Knowledge in Machine Learning: Understanding of attention based models, PyTorch, and GPU-accelerated computing. Problem-Solving Mindset: Strong analytical skills, with the ability to troubleshoot performance issues and propose innovative optimization strategies. Team Player: Excellent communication skills, eagerness to learn, and the ability to collaborate effectively with diverse teams.',
    prodi_tags: ['Sains Data', 'Robotika & AI', 'Teknik Elektro'],
    is_active: false,
    created_at: new Date(Date.now() - 12 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 12 * 86400000).toISOString(),
  },
  {
    id: 'vac-13',
    title: 'Data Analyst',
    company: 'Terra Softech',
    location: 'Aceh',
    source_url: 'https://www.linkedin.com/jobs/view/4443142422/',
    description: 'You have a true love for data. You have no problem tearing apart a problem and living inside a spreadsheet or data set to find the answer to any question. You have advanced knowledge of SQL, Excel, and Google Data Studio/Data Visualization tools, and enjoy working with SQL on a day-to-day basis. Experience with Marketing APIs, BigQuery or other cloud data warehouse tools (AWS, Snowflake, Databricks), ETL tools (such as Rivery, Looker, Supermetrics), and/or Python is a plus. You have a bachelor\'s degree in a relevant field and at least 1 year of experience working with marketing data and/or paid advertising campaigns, preferably in a fast-paced agency environment or team structure.',
    prodi_tags: ['Sains Data'],
    is_active: true,
    created_at: new Date(Date.now() - 13 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 13 * 86400000).toISOString(),
  },
  {
    id: 'vac-14',
    title: 'Business Intelligence Developer',
    company: 'Terra Softech',
    location: 'Aceh',
    source_url: 'https://www.linkedin.com/jobs/view/4443138573/',
    description: 'Should have experience in building PowerBI reports on top of Snowflake. Should have good understanding on Snowflake and ability to write SQL queries for data extraction in an optimal manner. Should have experience in Python as a programming language and its libraries. Should have the ability to read and understand existing python code and skilled to slightly tweak the code as needed for minor fixes / changes.',
    prodi_tags: ['Sains Data'],
    is_active: true,
    created_at: new Date(Date.now() - 14 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 14 * 86400000).toISOString(),
  },
  {
    id: 'vac-15',
    title: 'Project Deployment',
    company: 'Schneider Electric',
    location: 'Cikarang',
    source_url: 'https://www.linkedin.com/jobs/view/4442209235/',
    description: 'Active Bachelor Degree or Diploma student (max. 8th semester) in Industrial/ Mechanical/ Electrical/ Electronics/ Manufacturing Engineering or equivalent. Proficient in AutoCAD, LADM, MTM, Microsoft Office applications, Gerber software. Analytical with a keen eye for detail. Customer service and quality oriented. Good written and spoken English. Willing to be placed in Cikarang.',
    prodi_tags: ['Teknik Industri', 'Teknik Elektro'],
    is_active: false,
    created_at: new Date(Date.now() - 15 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 15 * 86400000).toISOString(),
  },
  {
    id: 'vac-16',
    title: 'Technical',
    company: 'Schneider Electric',
    location: 'Cikarang',
    source_url: 'https://www.linkedin.com/jobs/view/4441150709/',
    description: 'Currently pursuing a degree in Engineering, preferably in Automation, Electrical, Mechatronic or a related field. Knowledge of automation technologies, PLC programming, and control systems. Familiarity with industrial communication protocols such as Modbus, Profibus, or Ethernet/IP. Basic understanding of electrical circuits and wiring diagrams. Proficiency in programming languages such as ladder logic, structured text, or function block diagram. Strong problem-solving skills and attention to detail. Excellent communication and interpersonal skills.',
    prodi_tags: ['Teknik Elektro', 'Robotika & AI'],
    is_active: false,
    created_at: new Date(Date.now() - 16 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 16 * 86400000).toISOString(),
  },
  {
    id: 'vac-17',
    title: 'Project & Industrialization',
    company: 'Schneider Electric',
    location: 'Cikarang',
    source_url: 'https://www.linkedin.com/jobs/view/4444091416/',
    description: 'University students in Industrial Engineering or related majors. Preferable with strong organizational background. Good communicator in English & Bahasa. Strong drive in project management and execution. Continuous Improvement/CI and/or Kaizen experience background is a plus. Willing to intern for min. 6 months onsite at Cikarang. Willing to mobile work between Cikarang and key supplier (transport provided). Minimum offline academic responsibilities.',
    prodi_tags: ['Teknik Industri'],
    is_active: true,
    created_at: new Date(Date.now() - 17 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 17 * 86400000).toISOString(),
  },
  {
    id: 'vac-18',
    title: 'Technical Application',
    company: 'Schneider Electric',
    location: 'Cilandak',
    source_url: 'https://www.linkedin.com/jobs/view/4440748203/',
    description: 'Basic knowledge about control systems (PLCs, HMIs, VSDs, SCADAs, Servo Drives and Axis, industrial communication protocols...). Intermediate level about PLC & programming languages (ladder, python, sequencer, structure text...). Intermediate video editing skills. Proactive and structured work. Good organizational and analytical skills. Excellent communication skills and teamwork. Fluency in English. Active student with max 8th Semester of Faculty of Electrical Engineering, Faculty of Mechanical Engineering.',
    prodi_tags: ['Teknik Elektro', 'Robotika & AI'],
    is_active: true,
    created_at: new Date(Date.now() - 18 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 18 * 86400000).toISOString(),
  },
  {
    id: 'vac-19',
    title: 'Data Scientist',
    company: 'GoTo Group',
    location: 'Jakarta',
    source_url: 'https://www.linkedin.com/jobs/view/4439162257/',
    description: 'Proficiency in Python programming and basic data processing skills. Attention to detail, with a focus on maintaining high data quality standards. Strong communication skills for effective collaboration and documentation. Ability to work independently and as part of a team. Willingness to learn and adapt in a fast-paced environment. Ability to provide constructive feedback and contribute to team discussions.',
    prodi_tags: ['Sains Data', 'Robotika & AI'],
    is_active: true,
    created_at: new Date(Date.now() - 19 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 19 * 86400000).toISOString(),
  },
  {
    id: 'vac-20',
    title: 'Data Analyst',
    company: 'Seven Retail',
    location: 'Jakarta',
    source_url: 'https://www.linkedin.com/jobs/view/4434860287/',
    description: 'Final-year student or recent graduate in Statistics, Mathematics, Data Science, Computer Science, Business, Economics, Engineering, or a related field. Proficient in Microsoft Excel or Google Sheets, including formulas, pivot tables, charts, and lookup functions for data analysis and reporting. Familiar with SQL and exposure to Python, Tableau, Looker Studio, Power BI, or similar analytics tools through internships, academic projects, or personal projects. Strong analytical and problem-solving skills with the ability to interpret data and translate findings into clear business insights and recommendations. Detail-oriented, comfortable working with large datasets and managing multiple priorities in a fast-paced environment. Strong communication skills, a collaborative mindset, and a willingness to learn new tools and technologies.',
    prodi_tags: ['Sains Data'],
    is_active: false,
    created_at: new Date(Date.now() - 20 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 20 * 86400000).toISOString(),
  },
  {
    id: 'vac-21',
    title: 'Data Operation',
    company: 'Seven Retail',
    location: 'Jakarta',
    source_url: 'https://www.linkedin.com/jobs/view/4432792277/',
    description: 'Bachelor\'s or Master\'s degree in a quantitative or relevant field, preferably in Data Science, Statistics, Computer Science, Informatics System, or Engineering. Strong proficiency in SQL and fluent in Google Spreadsheet (pivot, lookup, etc); comfortable working with large datasets. Familiarity with BI tools (e.g. Tableau, Power BI, Looker). Experience with Python or R is a plus. Fluent in English and Bahasa Indonesia.',
    prodi_tags: ['Sains Data'],
    is_active: true,
    created_at: new Date(Date.now() - 21 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 21 * 86400000).toISOString(),
  },
  {
    id: 'vac-22',
    title: 'Engineering Support',
    company: 'PT Intecs Teknikatama Industri',
    location: 'Surabaya',
    source_url: 'https://www.linkedin.com/jobs/view/4449366263/',
    description: 'Bachelor\'s degree in Civil Engineering, Mechanical Engineering, or a related field. Fresh graduates are welcome to apply. Able to communicate in English, with at least passive proficiency (reading and writing). Strong communication, data analysis, administrative, and document management skills. Eager to learn, proactive, responsible, and able to work independently as well as in a team. Willing to participate in the internship program for the specified duration.',
    prodi_tags: ['Teknik Industri', 'Teknik Elektro'],
    is_active: true,
    created_at: new Date(Date.now() - 22 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 22 * 86400000).toISOString(),
  },
  {
    id: 'vac-23',
    title: 'Pre-Sales Engineer',
    company: 'Motorola Solutions',
    location: 'Jakarta',
    source_url: 'https://www.linkedin.com/jobs/view/4412585884/',
    description: 'Be pursuing a Bachelor\'s Degree or Professional Degree in Engineering (Electrical / Electronic) or equivalent course. Have good spoken and written communications skills in English and Bahasa Indonesia. Good interpersonal skills. Must be team-focused and highly self-motivated with a desire to explore new approaches and technology. Possess good project management skill set and be able to work independently on assigned projects. Be willing to travel within Indonesia occasionally. Business related travel expenses will be reimbursed.',
    prodi_tags: ['Teknik Elektro', 'Robotika & AI'],
    is_active: true,
    created_at: new Date(Date.now() - 23 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 23 * 86400000).toISOString(),
  },
  {
    id: 'vac-24',
    title: 'Research & Development',
    company: 'PT Sasa Inti',
    location: 'Jakarta',
    source_url: 'https://www.linkedin.com/jobs/view/4438220161/',
    description: 'Mahasiswa tingkat akhir yang tidak memiliki jadwal perkuliahan. Berasal dari jurusan Teknologi Pangan, Kimia Pangan, atau bidang terkait. Memiliki pemahaman tentang riset pangan, memastikan formulasi melalui aplikasi produk, serta menyiapkan dan menganalisis data riset. Bersedia bekerja dari kantor (WFO). Memiliki pola pikir positif dan mencerminkan nilai dasar SASA: Courage, Action-Oriented, Respectful, Enthusiastic (CARE).',
    prodi_tags: ['Rekayasa Nano'],
    is_active: true,
    created_at: new Date(Date.now() - 24 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 24 * 86400000).toISOString(),
  },
  {
    id: 'vac-25',
    title: 'Python Engineer',
    company: 'DMS',
    location: 'Yogyakarta',
    source_url: 'https://www.linkedin.com/jobs/view/4450933936/',
    description: 'Strong skills in Back-End Web Development and Software Development. Proficiency in Object-Oriented Programming (OOP) and general Programming skills. Experience or familiarity with working on Databases. Strong analytical and problem-solving skills. Eagerness to learn and explore new technologies. Bachelor\'s degree in Computer Science, Software Engineering, or related field (in progress or completed). Prior experience or coursework in Python programming is a plus.',
    prodi_tags: ['Sains Data'],
    is_active: true,
    created_at: new Date(Date.now() - 25 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 25 * 86400000).toISOString(),
  },
  {
    id: 'vac-26',
    title: 'AI Development',
    company: 'PT SMART Tbk',
    location: 'Jakarta',
    source_url: 'https://www.linkedin.com/jobs/view/4449790639/',
    description: 'Fresh graduate or active undergraduate student with no class to attend from Computer Science, Information Technology, Artificial Intelligence, Data Science, Computer Engineering, Mechanical Engineering, Industrial Engineering, or other related majors. Basic understanding of Artificial Intelligence, Machine Learning, Computer Vision, or Data Analytics. Familiar with Python for data processing and analysis. Experience with AI frameworks such as TensorFlow, PyTorch, OpenCV, or similar is an advantage. Familiarity with 3D design and animation software (e.g., Blender, SolidWorks, AutoCAD, or similar) is a plus. Strong analytical thinking, problem-solving, and communication skills. Able to work collaboratively with cross-functional teams and willing to support field implementation when required.',
    prodi_tags: ['Sains Data', 'Robotika & AI'],
    is_active: true,
    created_at: new Date(Date.now() - 26 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 26 * 86400000).toISOString(),
  },
  {
    id: 'vac-27',
    title: 'Procurement Logistics',
    company: 'PT SMART Tbk',
    location: 'Jakarta',
    source_url: 'https://www.linkedin.com/jobs/view/4451931745/',
    description: 'Active students or fresh graduates majoring in Industrial Engineering from reputable university. Proficient in Microsoft Excel is required. Detail-oriented, analytical, and comfortable working with data. Good communication and interpersonal skills. Fast learner, adaptable, and able to work independently or as part of a team. Available to work full-time from the office (Monday - Friday, 08.30 - 17.30) in Central Jakarta.',
    prodi_tags: ['Teknik Industri'],
    is_active: true,
    created_at: new Date(Date.now() - 27 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 27 * 86400000).toISOString(),
  },
  {
    id: 'vac-28',
    title: 'Site Intern',
    company: 'GSK',
    location: 'Jakarta',
    source_url: 'https://www.linkedin.com/jobs/view/4453867483/',
    description: 'Student in reputable University. Major in Pharmaceuticals or natural Science. Proficient in Microsoft Office (Excel, Word, PowerPoint). Knowledge of SAP.',
    prodi_tags: ['Rekayasa Nano'],
    is_active: true,
    created_at: new Date(Date.now() - 28 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 28 * 86400000).toISOString(),
  },
  {
    id: 'vac-29',
    title: 'Operations',
    company: 'GE Vernova',
    location: 'Bandung',
    source_url: 'https://www.linkedin.com/jobs/view/4437809724/',
    description: 'Currently pursuing a Bachelor\'s or Master\'s degree in Industrial Engineering, Mechanical Engineering, Materials Engineering, or other related majors. Proficiency in Microsoft Office (Excel, Word, PowerPoint) and familiarity with data analysis tools is a plus. Excellent communication and interpersonal skills, capable of working effectively in a team environment. Having organizational experiences is a desired qualification. Familiarity with various engineering design software is a plus. Ability to communicate in English (speaking, listening, and writing).',
    prodi_tags: ['Teknik Industri'],
    is_active: true,
    created_at: new Date(Date.now() - 29 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 29 * 86400000).toISOString(),
  },
  {
    id: 'vac-30',
    title: 'Packaging Engineer',
    company: 'L\'Oréal',
    location: 'Bekasi',
    source_url: 'https://www.linkedin.com/jobs/view/4449382570/',
    description: 'A final-year student with a mandatory internship program from your University. An academic background in Mechanical, Industrial, or Packaging Engineering. A strong willingness to learn packaging testing protocols, line trials, and optimization. Excellent communication skills in both Bahasa Indonesia and English. A detail-oriented mindset with basic technical background or familiarity with measurement tools. An interest or skill in creating digital forms and documentation.',
    prodi_tags: ['Teknik Industri', 'Rekayasa Nano'],
    is_active: true,
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 30 * 86400000).toISOString(),
  },
  {
    id: 'vac-31',
    title: 'Manufacturing Supply Chain',
    company: 'L\'Oréal',
    location: 'Bekasi',
    source_url: 'https://www.linkedin.com/jobs/view/4455621908/',
    description: 'A final-year student (preferably majoring in Engineering or a related field) with a mandatory university internship requirement. Basic skills in Microsoft Excel for data management, tracking, and reporting. A strong detail-oriented mindset with a natural comfort for managing data and tracking processes. Excellent communication skills in both Bahasa Indonesia and English. A proactive attitude and the ability to adapt quickly to a fast-paced manufacturing environment.',
    prodi_tags: ['Teknik Industri'],
    is_active: true,
    created_at: new Date(Date.now() - 31 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 31 * 86400000).toISOString(),
  },
  {
    id: 'vac-32',
    title: 'Mechatronic Engineering',
    company: 'ALVA',
    location: 'Bekasi',
    source_url: 'https://www.linkedin.com/jobs/view/4448403233/',
    description: 'Contribute to mechanical and electrical design for the development of ALVA product, including feasibility studies and exploratory engineering calculations for EV-related concepts. Support the development, assembly, and testing of prototypes and proof-of-concept systems, including batteries and other EV subsystems. Participate in research and exploration of new concepts and technologies related to electric vehicles. Collaborate closely with cross-functional teams such as R&D, Quality, and Manufacturing to troubleshoot and solve complex technical issues. Gain hands-on exposure across multiple engineering domains, including batteries, motors, structural components, frames, and swing arms.',
    prodi_tags: ['Teknik Elektro', 'Robotika & AI'],
    is_active: true,
    created_at: new Date(Date.now() - 32 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 32 * 86400000).toISOString(),
  },
  {
    id: 'vac-33',
    title: 'Data Center Engineer',
    company: 'ST Telemedia Global Data Centres',
    location: 'Cikarang',
    source_url: 'https://www.linkedin.com/jobs/view/4452197167/',
    description: 'Final year student, bachelor degree in Electrical & Mechanical Engineering. Available for a full-time internship placement in Cikarang. Open to rotating shifts and capable of adapting to different schedules. Strong interest in Data Center, Critical Facilities, Building Services, or Industrial Operations. Basic understanding of: Electrical Power Systems, HVAC / Cooling Systems, Mechanical Equipment and Facility Maintenance. Able to read and understand technical drawings and engineering documentation. Good analytical thinking and problem-solving skills. Proactive, detail-oriented, and eager to learn. Able to communicate effectively and work collaboratively in a team environment.',
    prodi_tags: ['Teknik Elektro', 'Teknik Industri'],
    is_active: true,
    created_at: new Date(Date.now() - 33 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 33 * 86400000).toISOString(),
  },
  {
    id: 'vac-34',
    title: 'Technical',
    company: 'ABB',
    location: 'Jakarta',
    source_url: 'https://www.linkedin.com/jobs/view/4456733914/',
    description: 'You are currently pursuing a bachelor\'s degree in engineering, specializing in Electrical, Electronics, Mechanical, Mechatronics, Computer Science, Industrial Engineering or related fields. You are comfortable communicating in English. You are eager to learn and grow through diverse experiences and from different perspectives. You can collaborate effectively and communicate your progress clearly within a team.',
    prodi_tags: ['Teknik Elektro', 'Teknik Industri', 'Robotika & AI'],
    is_active: true,
    created_at: new Date(Date.now() - 34 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 34 * 86400000).toISOString(),
  },
  {
    id: 'vac-35',
    title: 'Field Application Engineer',
    company: 'Sangfor Technologies',
    location: 'Jakarta',
    source_url: 'https://www.linkedin.com/jobs/view/4445450293/',
    description: 'Final year students currently pursuing of Bachelor\'s degree in engineering, Cyber Security, Computer science, information system or related field. Positive and professional working attitude, ability to work under minimum supervision. Analytical and problem-solving abilities. Communication skills in Bahasa and knowledge of English. Willingness to work from office based in Jakarta.',
    prodi_tags: ['Teknik Elektro', 'Teknik Industri'],
    is_active: true,
    created_at: new Date(Date.now() - 35 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 35 * 86400000).toISOString(),
  },
  {
    id: 'vac-36',
    title: 'Pre-Sales Engineer',
    company: 'Sangfor Technologies',
    location: 'Jakarta',
    source_url: 'https://www.linkedin.com/jobs/view/4445450293/',
    description: 'Final year students currently pursuing Bachelor\'s degree in engineering, Cyber Security, Computer Science, Information System or related field. Positive and professional working attitude, ability to work under minimum supervision. Analytical and problem-solving abilities. Communication skills in Bahasa and knowledge of English. Willingness to work from office based in Jakarta.',
    prodi_tags: ['Teknik Elektro', 'Teknik Industri'],
    is_active: true,
    created_at: new Date(Date.now() - 36 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 36 * 86400000).toISOString(),
  },
  {
    id: 'vac-37',
    title: 'Assistant Facilities Engineer',
    company: 'DayOne',
    location: 'Batam',
    source_url: 'https://www.linkedin.com/jobs/view/4455241214/',
    description: 'Currently pursuing or recently completed a Bachelor\'s degree in Civil, Mechanical, Electrical, Building Services Engineering, or a related field. Strong interest in data center operations, facilities, or critical engineering systems. Basic understanding of engineering principles (MEP preferred). Good analytical, troubleshooting, and problem-solving mindset. Good verbal and written communication skills. Willingness to learn, take instructions, and work in a team-based environment.',
    prodi_tags: ['Teknik Elektro', 'Teknik Industri', 'Robotika & AI'],
    is_active: true,
    created_at: new Date(Date.now() - 37 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 37 * 86400000).toISOString(),
  },
  {
    id: 'vac-38',
    title: 'Process Excellence',
    company: 'PT Link Net Tbk',
    location: 'Tangerang Selatan',
    source_url: 'https://www.linkedin.com/jobs/view/4452437032/',
    description: 'Active college student or fresh graduate in System Information, Industrial Engineering, or related fields. Basic understanding of business processes and documentation. Familiar with Microsoft Visio, Draw.io, or similar process diagramming tools. Proficient in Microsoft Excel, Word, and PowerPoint. Detail-oriented, organized, and willing to learn. Willing to Work On-site in BSD, South Tangerang.',
    prodi_tags: ['Teknik Industri'],
    is_active: true,
    created_at: new Date(Date.now() - 38 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 38 * 86400000).toISOString(),
  },
  {
    id: 'vac-39',
    title: 'Packaging Development',
    company: 'MOP Beauty',
    location: 'Jakarta',
    source_url: 'https://www.linkedin.com/jobs/view/4449305228/',
    description: 'Assist in researching packaging trends, materials, and innovative solutions within the beauty industries. Support the sourcing process by gathering information from suppliers, preparing vendor comparison sheets, and coordinating packaging samples. Help review packaging designs, dielines, and prototypes to ensure alignment with brand standards and functional requirements. Assist in documentation and data management for packaging specifications, testing reports, and supplier records. Support compatibility and stability testing coordination between packaging and product formulations. Collaborate with the Product Development and Creative teams to ensure packaging concepts align with campaign direction and design intent. Conduct research on eco-friendly and sustainable packaging materials. Participate in internal meetings and brainstorming sessions, contributing ideas for innovative and practical packaging improvements.',
    prodi_tags: ['Teknik Industri', 'Rekayasa Nano'],
    is_active: true,
    created_at: new Date(Date.now() - 39 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 39 * 86400000).toISOString(),
  },
  {
    id: 'vac-40',
    title: 'Product Development & Category Expansion',
    company: 'APP Group',
    location: 'Thamrin',
    source_url: 'https://www.linkedin.com/jobs/view/4449369807/',
    description: 'Final year or fresh graduate from Business Management, Industrial Engineering or any related fields. Proficient in Microsoft Excel.',
    prodi_tags: ['Teknik Industri'],
    is_active: true,
    created_at: new Date(Date.now() - 40 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 40 * 86400000).toISOString(),
  },
  {
    id: 'vac-41',
    title: 'Product Management',
    company: 'APP Group',
    location: 'Karawang',
    source_url: 'https://www.linkedin.com/jobs/view/4449369807/',
    description: 'Final year student or fresh graduate from Industrial Engineering or any related fields. Have prior internship experience in Procurement or Supply chain is a plus. Proficient in Microsoft Excel and fluent in English.',
    prodi_tags: ['Teknik Industri'],
    is_active: true,
    created_at: new Date(Date.now() - 41 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 41 * 86400000).toISOString(),
  },
  {
    id: 'vac-42',
    title: 'Procurement Packaging',
    company: 'APP Group',
    location: 'Serpong',
    source_url: 'https://www.linkedin.com/jobs/view/4449369807/',
    description: 'Final year student or fresh graduate from Industrial Engineering or any related fields. Have prior internship experience in Procurement or Supply chain is a plus. Proficient in Microsoft Excel and fluent in English.',
    prodi_tags: ['Teknik Industri'],
    is_active: true,
    created_at: new Date(Date.now() - 42 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 42 * 86400000).toISOString(),
  },
  {
    id: 'vac-43',
    title: 'Procurement MRO',
    company: 'APP Group',
    location: 'Serpong',
    source_url: 'https://www.linkedin.com/jobs/view/4449369807/',
    description: 'Final year student or fresh graduate from Industrial Engineering or any related fields. Have prior internship experience in Procurement or Supply chain is a plus. Proficient in Microsoft Excel and fluent in English.',
    prodi_tags: ['Teknik Industri'],
    is_active: true,
    created_at: new Date(Date.now() - 43 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 43 * 86400000).toISOString(),
  },
  {
    id: 'vac-44',
    title: 'Procurement Transportation',
    company: 'APP Group',
    location: 'Serpong',
    source_url: 'https://www.linkedin.com/jobs/view/4449369807/',
    description: 'Final year student or fresh graduate from Industrial Engineering or any related fields. Have prior internship experience in Procurement or Supply chain is a plus. Proficient in Microsoft Excel and fluent in English.',
    prodi_tags: ['Teknik Industri'],
    is_active: true,
    created_at: new Date(Date.now() - 44 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 44 * 86400000).toISOString(),
  },
  {
    id: 'vac-45',
    title: 'Procurement Forestry',
    company: 'APP Group',
    location: 'Serpong',
    source_url: 'https://www.linkedin.com/jobs/view/4449369807/',
    description: 'Final year student or fresh graduate from Industrial Engineering or any related fields. Have prior internship experience in Procurement or Supply chain is a plus. Proficient in Microsoft Excel and fluent in English.',
    prodi_tags: ['Teknik Industri'],
    is_active: true,
    created_at: new Date(Date.now() - 45 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 45 * 86400000).toISOString(),
  },
  {
    id: 'vac-46',
    title: 'Capex Procurement',
    company: 'APP Group',
    location: 'Serpong',
    source_url: 'https://www.linkedin.com/jobs/view/4449369807/',
    description: 'Final year student or fresh graduate from Industrial Engineering or any related fields. Have prior internship experience in Procurement or Supply chain is a plus. Proficient in Microsoft Excel and fluent in English.',
    prodi_tags: ['Teknik Industri'],
    is_active: true,
    created_at: new Date(Date.now() - 46 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 46 * 86400000).toISOString(),
  },
];

// Aliases for compatibility
export const INITIAL_MOCK_JOBS = INITIAL_MOCK_VACANCIES;
export const FTMM_PROGRAMS = FTMM_PRODI_LIST;
